### ISSUE TITLE
Add support for .xml (drawio app) and .km (Mind Map app)

### ISSUE THREAD

**Issue by jpubb** [nextcloud/files_fulltextsearch#98] opened 2020-09-25 21:45 UTC
Enhancement:  

The Drawio and "Mind Map" nextcloud apps are fantastic! They respectively output .xml (or .drawio) and .km files which would be very helpful to be included in indexing. I have tried searching for terms within these files but do not get any results.

**Comment by acsfer** [comment] 2021-09-15 11:21
Duplicate of #21

**Closed** 2021-09-15 11:21 UTC
Labels: duplicate
