### ISSUE TITLE
Nexcloud 27 crash

### ISSUE THREAD

**Issue by sergiupapuc** [nextcloud/files_fulltextsearch#233] opened 2023-06-20 04:19 UTC
Hello

On Nextcloud 27 with Groupfolder install, app Files_fulltextsearch crash the system...

**Comment by 3038922** [comment] 2023-06-20 16:20
me tooo

**Comment by prolibre** [comment] 2023-06-20 16:40
An update should be posted shortly. The problem is known.

https://github.com/nextcloud/files_fulltextsearch/pull/232

**Comment by btakita** [comment] 2023-06-30 04:58
Any word on the update?

**Comment by prolibre** [comment] 2023-07-01 05:27
> Any word on the update?

it's strange indeed

**Comment by hanserasmus** [comment] 2023-07-03 15:33
Same problem here. Disabling fulltextsearch make the server available again, but as soon as I enable it, I get 500 Internal server error.

**Comment by DrMurx** [comment] 2023-07-05 07:56
The issue has apparently been fixed in #227 and #231, but the changes didn't make it in 27.0.0 release, and no new version has been released since. You can try applying the patchsets yourself, but there might be a reason why @ArtificialOwl hasn't released a 27.0.1 yet (see my request in #234).

**Comment by ArtificialOwl** [comment] 2023-07-05 08:51
i'll try to do a release today

**Comment by angyen** [comment] 2023-07-19 05:39
> i'll try to do a release today
Thank you!

**Comment by prolibre** [comment] 2023-07-19 10:06
> > Thank you!

2 weeks ago :-)

**Comment by jacotec** [comment] 2023-07-20 18:25
@ArtificialOwl Whats the status here? I have 500 crashes after updating two instances and found this is the root cause. Update was promised two weeks ago ...

**Comment by prolibre** [comment] 2023-07-21 07:42
@jacotec it all smacks of a developer's vacation :-)

**Comment by jacotec** [comment] 2023-07-21 07:47
Yap :-)
Just wondered because he wrote he'll push the update two weeks ago.

I've meanwhile patched the two commits manually.

**Comment by angyen** [comment] 2023-07-22 01:58
Good things require patience...
The developers doesn't owe us anything. Maybe they are really caught up with works or some other incidence, we just have to be patient and wait for their update...
Anyway by disabling the app we can still use nextcloud without issue, so we should just be patient.

**Comment by RuudschMaHinda** [comment] 2023-07-22 10:12
I agree with you wholeheartedly! Was caught up in emotions when that happened. The app should not not be labeled as ready for update though. Having to go through logs and disable apps via the command line isn't fun. Always gives me half a heart attack when after an update I am supposed to ask the admin XD
I should have just mentioned that this is still the case for updating to NC 27.0.1 without the implied accusations.

**Comment by angyen** [comment] 2023-07-25 02:24
I've also patched the two commits manually.
but I have ran into the problem as below when I do indexing
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 211816448 bytes) in /config/www/nextcloud/apps/fulltextsearch_elasticsearch/vendor/elastic/transport/src/Serializer/JsonSerializer.php on line 48

Note that I have already allowed more memory as it suggested and if I allocate more memory in php (I increased it to 2GB) then I will face another problem with elasticsearch

java.lang.outofmemoryerror: java heap space

I have since increase the java heap space on elasticsearch to 8GB but still it gave me the same error.

I think it's either my manual patching is erronous or there is some setting which I din do correctly.

**Comment by angyen** [comment] 2023-07-25 07:47
> 

Just found out that I have set the Maximum file size to index (in Mb).: 128mb which was too high. reduced it to 1mb make the indexing works and completed without error.
How many mb you all set for your Maximum file size to index (in Mb)?

**Comment by hanserasmus** [comment] 2023-08-31 14:32
@ArtificialOwl I know this is a project that you do in your free time, so first off, thank you for that. Have you perhaps been able to make the official release yet that will fix this bug?

**Comment by prolibre** [comment] 2023-08-31 16:50
> @ArtificialOwl I know this is a project that you do in your free time, so first off, thank you for that. Have you perhaps been able to make the official release yet that will fix this bug?

This has been fixed for a while now.

**Comment by hanserasmus** [comment] 2023-08-31 17:04
@prolibre I apologise. I missed it. I have updated my NC 27.0.0 version now, I have Groupfolders enabled and it does indeed seem like it is working. Thank you.

**Closed** 2023-09-01 22:20 UTC
