### ISSUE TITLE
Result count wrong or result doesn't show up

### ISSUE THREAD

**Issue by kitzler-walli** [nextcloud/files_fulltextsearch#85] opened 2020-02-24 14:49 UTC
### Steps to reproduce
I search for "node_modules" in my nextcloud and the resultpage shows 7692 results but only displays about 20.
(I recently upgraded to 18.0.1 from 17.0.3 - probably a reindex necessary?)

![Screenshot 2020-02-24 at 15 42 53](https://user-images.githubusercontent.com/1926992/75162080-3a2e4380-571d-11ea-9150-ccede94cc2b7.png)

### Expected behaviour
Either the results should be displayed or correctly counted.

### Actual behaviour
Result count and displayed items count mismatch.

## Server configuration detail

**Operating system:** Linux 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** pgsql PostgreSQL 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0, 64-bit

**PHP version:** 

7.2.24-0ubuntu0.18.04.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, json, igbinary, apcu, PDO, xml, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imap, intl, redis, ldap, exif, pdo_pgsql, pgsql, Phar, posix, readline, shmop, SimpleXML, smbclient, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 18.0.1 - 18.0.1.3

**Updated from an older Nextcloud/ownCloud or fresh install:** 
Updated from 17.0.3 recently.

**Where did you install Nextcloud from:** 

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - calendar: 2.0.1
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.1.8
 - dav: 1.14.0
 - deck: 0.8.0
 - documentserver_community: 0.1.5
 - extract: 1.2.3
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_antivirus: 2.2.1
 - files_fulltextsearch: 1.4.1
 - files_pdfviewer: 1.7.0
 - files_reader: 1.2.3
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - fulltextsearch: 1.4.1
 - fulltextsearch_elasticsearch: 1.5.0
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - mail: 1.1.2
 - news: 14.1.3
 - nextcloud_announcements: 1.7.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - onlyoffice: 4.1.4
 - password_policy: 1.8.0
 - photos: 1.0.0
 - previewgenerator: 2.2.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - spreed: 8.0.4
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - tasks: 0.11.3
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - twofactor_totp: 4.1.2
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - encryption
 - files_external
 - files_mindmap
 - notes
 - user_ldap

```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36

**Comment by acsfer** [comment] 2021-09-15 11:09
Can you please confirm this still hapens with both latest versions of Nexcloud and `files_fulltextsearch` apps?

**Comment by joshtrichards** [comment] 2023-10-02 20:47
Closing due to no further confirmations of reproducibility after 2+ years. Feel free to open a new issue or follow-up if this is actually still valid.

**Closed by joshtrichards** 2023-10-02 20:47 UTC
Labels: bug, 0. Needs triage, needs info
