### ISSUE TITLE
How to enable Fulltextsearch to all users (including non admin)?

### ISSUE THREAD

**Issue by kevinkuan1969** [nextcloud/files_fulltextsearch#222] opened 2023-06-05 06:44 UTC

**Comment by kevinkuan1969** [comment] 2023-06-05 06:59
Managed to setup Elasticsearch 8.7.1 in Nextcloud 26.0.2 and both works successfully for two users who are adminstrator role.

When login to another new user which is not adminstrator and discovered nothing return in UI search result. Also issue the following command to confirm:

  sudo -u www-data php occ fulltextsearch:search "userxxx" xxxxxxx

search
> Deck
> Files

In the command of php occ filetextsearh:live, the elasticsearch seems to perform the indexing but always status is waiting
![image](https://github.com/nextcloud/files_fulltextsearch/assets/80019930/09a03174-3048-4ddf-9202-e8aad3c669a1)

Kindly advise is the elasticsearch to allow install in Nextcloud only limit for certain number of users or any settings need to be applied. Thanks.

**Comment by kevinkuan1969** [comment] 2023-06-06 09:50
Using command below to check the difference between the two documents from successful user vs non successful user. The non successful user who cannot return any result from Elasticsearch contains NULL value in User field.

 sudo -u www-data php occ fulltextsearch:document:platform files
![image](https://github.com/nextcloud/files_fulltextsearch/assets/80019930/d0ba1c7e-1ea4-4fd6-a94f-ed7195355851)
![image](https://github.com/nextcloud/files_fulltextsearch/assets/80019930/446c1da9-3735-44ca-93f0-eb5a4c85aa55)

**Comment by joshtrichards** [comment] 2023-10-02 20:11
Closing as a duplicate of nextcloud/fulltextsearch#751

**Closed by joshtrichards** 2023-10-02 20:11 UTC
