### ISSUE TITLE
Error using folder share via public link on upload or delete files (FilesEvents.php)

### ISSUE THREAD

**Issue by ftempra** [nextcloud/files_fulltextsearch#31] opened 2019-01-18 11:19 UTC
- NC-15.0.2
- Full text search 1.2.3
- Full text search - Elasticsearch Platform 1.2.2
- Full text search - Files 1.2.3

If a file is uploaded or deleted via a public link share, since the userID is null, the script in FilesEvents.php reports an error on line 135 and 211 and the list of files in the browser is not updated.

In order to use the upload via link to the public share, I temporarily changed line 135 and 211 of the FilesEvents.php file as follows:

**original line 135:**
    $file = $this->filesService->getFileFromPath($this->userId, $path);
   if ($this->configService->isCloudVersionAtLeast(15, 0, 1)) {
         $this->fullTextSearchManager->createIndex(
        'files', (string)$file->getId(), $this->userId, IIndex::INDEX_FULL
         );
   }
**replaced with:**
    if ($this->userId) {
      $file = $this->filesService->getFileFromPath($this->userId, $path);
      if ($this->configService->isCloudVersionAtLeast(15, 0, 1)) {
  		$this->fullTextSearchManager->createIndex(
		'files', (string)$file->getId(), $this->userId, IIndex::INDEX_FULL
                 );
       }

**original line 211:**
	$file = $this->filesService->getFileFromPath($this->userId, $path);
	$this->fullTextSearchManager->updateIndexStatus(
		'files', (string)$file->getId(), IIndex::INDEX_REMOVE, true
                );
**replaced with:**
	if ($this->userId) {
		$file = $this->filesService->getFileFromPath($this->userId, $path);
		$this->fullTextSearchManager->updateIndexStatus(
			'files', (string)$file->getId(), IIndex::INDEX_REMOVE, true
                	);
              }

**Comment by linuxrrze** [comment] 2019-03-07 20:10
I can confirm the problem with the following setup:

Nextcloud 15.0.5

Full text search	1.2.5		
Full text search - Bookmarks	1.2.0		
Full text search - Elasticsearch Platform	1.2.4	
Full text search - Files	1.2.6

When uploading or deleting multiple files at once on a folder share via public link, this error occurs.

However there seems to be some kind of device/browser dependency, that I couldn't figure out right now - on some devices/browsers it works while at the same time it fails on others.

I'll give the above patches a try, as soon as I figured out how what combination causes the problem.

For now I have to disable the files_fulltextsearch app to get rid of this errors.

**Comment by theroch** [comment] 2019-03-12 08:33
I can confirm the problem with the following setup too:

Nextcloud 15.0.5

Full text search 1.2.5
Full text search - Bookmarks 1.2.0
Full text search - Elasticsearch Platform 1.2.4
Full text search - Files 1.2.6

Using public share on smb mount.

Stack trace is:
```
{
  "reqId": "UOSbh9J0qiGyR7xIBUwJ",
  "level": 3,
  "time": "2019-03-12T07:43:12+00:00",
  "remoteAddr": "192.168.0.2",
  "user": "--",
  "app": "public",
  "method": "PUT",
  "url": "/public.php/webdav/test.pdf",
  "message": {
    "Exception": "TypeError",
    "Message": "Argument 1 passed to OCA\\Files_FullTextSearch\\Service\\FilesService::getFileFromPath() must be of the type string, null given, called in /path/to/nextcloud/apps/files_fulltextsearch/lib/Events/FilesEvents.php on line 137",
    "Code": 0,
    "Trace": [
      {
        "file": "/path/to/nextcloud/apps/files_fulltextsearch/lib/Events/FilesEvents.php",
        "line": 137,
        "function": "getFileFromPath",
        "class": "OCA\\Files_FullTextSearch\\Service\\FilesService",
        "type": "->",
        "args": [
          null,
          "/path/to//test.pdf"
        ]
      },
      {
        "file": "/path/to/nextcloud/apps/files_fulltextsearch/lib/Hooks/FilesHooks.php",
        "line": 74,
        "function": "onNewFile",
        "class": "OCA\\Files_FullTextSearch\\Events\\FilesEvents",
        "type": "->",
        "args": [
          {
            "path": "/path/to//test.pdf"
          }
        ]
      },
      {
        "file": "/path/to/nextcloud/lib/private/legacy/hook.php",
        "line": 106,
        "function": "onNewFile",
        "class": "OCA\\Files_FullTextSearch\\Hooks\\FilesHooks",
        "type": "::",
        "args": [
          {
            "path": "/path/to//test.pdf"
          }
        ]
      },
      {
        "file": "/path/to/nextcloud/apps/dav/lib/Connector/Sabre/File.php",
        "line": 346,
        "function": "emit",
        "class": "OC_Hook",
        "type": "::",
        "args": [
          "OC_Filesystem",
          "post_create",
          {
            "path": "/path/to//test.pdf"
          }
        ]
      },
      {
        "file": "/path/to/nextcloud/apps/dav/lib/Connector/Sabre/File.php",
        "line": 278,
        "function": "emitPostHooks",
        "class": "OCA\\DAV\\Connector\\Sabre\\File",
        "type": "->",
        "args": [
          false
        ]
      },
      {
        "file": "/path/to/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php",
        "line": 156,
        "function": "put",
        "class": "OCA\\DAV\\Connector\\Sabre\\File",
        "type": "->",
        "args": [
          null
        ]
      },
      {
        "file": "/path/to/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 1096,
        "function": "createFile",
        "class": "OCA\\DAV\\Connector\\Sabre\\Directory",
        "type": "->",
        "args": [
          "test.pdf",
          null
        ]
      },
      {
        "file": "/path/to/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
        "line": 525,
        "function": "createFile",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          "test.pdf",
          null,
          null
        ]
      },
      {
        "function": "httpPut",
        "class": "Sabre\\DAV\\CorePlugin",
        "type": "->",
        "args": [
          {
            "absoluteUrl": "https://my.server.local/public.php/webdav/test.pdf",
            "__class__": "Sabre\\HTTP\\Request"
          },
          {
            "__class__": "Sabre\\HTTP\\Response"
          }
        ]
      },
      {
        "file": "/path/to/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php",
        "line": 105,
        "function": "call_user_func_array",
        "args": [
          [
            {
              "__class__": "Sabre\\DAV\\CorePlugin"
            },
            "httpPut"
          ],
          [
            {
              "absoluteUrl": "https://my.server.local/public.php/webdav/test.pdf",
              "__class__": "Sabre\\HTTP\\Request"
            },
            {
              "__class__": "Sabre\\HTTP\\Response"
            }
          ]
        ]
      },
      {
        "file": "/path/to/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 479,
        "function": "emit",
        "class": "Sabre\\Event\\EventEmitter",
        "type": "->",
        "args": [
          "method:PUT",
          [
            {
              "absoluteUrl": "https://my.server.local/public.php/webdav/test.pdf",
              "__class__": "Sabre\\HTTP\\Request"
            },
            {
              "__class__": "Sabre\\HTTP\\Response"
            }
          ]
        ]
      },
      {
        "file": "/path/to/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 254,
        "function": "invokeMethod",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          {
            "absoluteUrl": "https://my.server.local/public.php/webdav/test.pdf",
            "__class__": "Sabre\\HTTP\\Request"
          },
          {
            "__class__": "Sabre\\HTTP\\Response"
          }
        ]
      },
      {
        "file": "/path/to/nextcloud/apps/dav/appinfo/v1/publicwebdav.php",
        "line": 107,
        "function": "exec",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/path/to/nextcloud/public.php",
        "line": 79,
        "args": [
          "/path/to/nextcloud/apps/dav/appinfo/v1/publicwebdav.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/path/to/nextcloud/apps/files_fulltextsearch/lib/Service/FilesService.php",
    "Line": 362,
    "CustomMessage": "--"
  },
  "userAgent": "Mozilla/5.0 Firefox/65.0",
  "version": "15.0.5.3"
}
```

**Comment by daita** [comment] 2019-04-07 12:36
fixed in last release (nc15 & 16)

**Comment by ftempra** [comment] 2019-04-10 13:11
Many thanks

**Closed** 2019-04-10 13:11 UTC

**Comment by enboig** [comment] 2019-05-21 12:05
It isn't in files_fulltextsearch v1.3.1
