### ISSUE TITLE
OnlyOffice and Collabora Integration not working when enabling Full text search - Files

### ISSUE THREAD

**Issue by guenterzimmermann** [nextcloud/files_fulltextsearch#83] opened 2020-01-18 12:46 UTC
Versions: NC 18.0.0.10, Collabora Online 3.5.1, OnlyOffice Integration App 4.1.1., Full text search - Files 1.4.0. 
Issue: When enabling Full text search - Files, both integration apps (onlyoffice and collabora) stop working. Context menu integration is not working anymore then, even so "New" Menu lost all entries for those documents. Documents can not be opend with Onlyoffice or Collabora anymore, instead a download dialog is presented.
As soon as you didable Full text search - Files, everything is working again.

**Comment by z49x2vmq** [comment] 2020-01-20 10:28
Additionally "Deleted files" shows nothing when "Full test search - Files" is enabled. When it is disabled, I can see the list of delete files by clicking "Deleted files"

**Comment by janLo** [comment] 2020-01-20 14:55
I've the same issue. What I can see is that this:
https://github.com/nextcloud/files_fulltextsearch/blob/master/js/files.js#L76
causes an uncaught exception because `window.FileActions` is undefined. If I comment all occurrences of `window.FileActions` out it works fine.

**Comment by janLo** [comment] 2020-01-20 14:59
`window.FileActions` got removed: https://github.com/nextcloud/server/commit/5e4eda1ae0ea0ee7e690fee1017dae873a1a7512#diff-6cfa15099b7891cdc06cd1108f80438f

**Comment by Fin3** [comment] 2020-01-21 07:27
janLo, i'm sorry but i can't understand... is a server issue or a files_fulltextsearch issue?

What should we do to solve the issue in our nextcloud installation?

Thank you in advance

**Comment by janLo** [comment] 2020-01-21 08:37
It's a fulltextsearch files issue. It's not compatible with NC 18 in the current installation. 
It can be worked around by either disabling or commenting out all occurrences (lines) of `window.FileActions` in is/files.js.

**Comment by ShinjiLE** [comment] 2020-01-21 10:08
File-move-copy-dialog is also affect of this .

**Comment by jurgenhaas** [comment] 2020-01-24 07:19
Confirmed, I have the same issue related to Collabora.

**Comment by ShinjiLE** [comment] 2020-01-25 13:43
My Problem is solved with 1.4.1 . 
Thanks !

**Comment by Tamsy** [comment] 2020-01-26 01:10
Unfortunately, 1.4.1 on NC 18 only partially addresses the problem.
While reactivating Full TText Search - Files after the 1.4.1-update now starts OnlyOffice after choosing an office file, the choosen file never gets fully loaded and displayed.

The following gets writen into nextcloud.log:

OCA\DocumentServer\Document\DocumentConversionException: namespace error : Namespace prefix a on prstTxWarp is not defined <a:prstTxWarp prst="textPlain"><a:avLst/></a:prstTxWarp> ^ namespace error : Namespace prefix a on avLst is not defined <a:prstTxWarp prst="textPlain"><a:avLst/></a:prstTxWarp> ^ namespace error : Namespace prefix a on prstGeom is not defined <a:prstGeom prst="rect"><a:avLst/></a:prstGeom> ^ namespace error : Namespace prefix a on avLst is not defined <a:prstGeom prst="rect"><a:avLst/></a:prstGeom> ^ namespace error : Namespace prefix a on srgbClr is not defined ="36"/><w:szCs w:val="36"/><w14:textFill><w14:solidFill><a:srgbClr val="C0C0C0" ^ namespace error : Namespace prefix a on srgbClr is not defined ="36"/><w:szCs w:val="36"/><w14:textFill><w14:solidFill><a:srgbClr val="C0C0C0" ^ namespace error : Namespace prefix a on prstTxWarp is not defined <a:prstTxWarp prst="textPlain"><a:avLst/></a:prstTxWarp> ^ namespace error : Namespace prefix a on avLst is not defined <a:prstTxWarp prst="textPlain"><a:avLst/></a:prstTxWarp> ^ namespace error : Namespace prefix a on prstGeom is not defined <a:prstGeom prst="rect"><a:avLst/></a:prstGeom> ^ namespace error : Namespace prefix a on avLst is not defined <a:prstGeom prst="rect"><a:avLst/></a:prstGeom> ^ namespace error : Namespace prefix a on srgbClr is not defined ="36"/><w:szCs w:val="36"/><w14:textFill><w14:solidFill><a:srgbClr val="C0C0C0" ^ namespace error : Namespace prefix a on srgbClr is not defined ="36"/><w:szCs w:val="36"/><w14:textFill><w14:solidFill><a:srgbClr val="C0C0C0" ^

After disabling Full Text Search - Files  Office-files can be opened again as they should.

**Comment by Usodiariom** [comment] 2020-04-15 22:28
I have the same problem.

- On a **VPS** installed a month ago, perfect Onlyoffice works

- In a new installation today on a **Raspberry Pi 4 4GB** it only does the download action, it does not open Onlyoffice, even install 18.0.0 and 18.0.3, but it does not work, the files are only downloaded.

Can something be done?

**Comment by joshtrichards** [comment] 2024-03-01 19:46
Fixed in 7f453f2

**Closed by joshtrichards** 2024-03-01 19:46 UTC
Labels: bug, 0. Needs triage, integration
