### ISSUE TITLE
unhandled exception in ExternalFilesService.php (indexing works, crashes after that)

### ISSUE THREAD

**Issue by p3pp0** [nextcloud/files_fulltextsearch#33] opened 2019-01-24 00:26 UTC
An unhandled exception has been thrown:
Error: Call to a member function getStorage() on null in /var/www/nextcloud/apps/files_fulltextsearch/lib/Service/ExternalFilesService.php:291
Stack trace:
#0 /var/www/nextcloud/apps/files_fulltextsearch/lib/Service/ExternalFilesService.php(316): OCA\Files_FullTextSearch\Service\ExternalFilesService->getExternalMountById(2)
#1 /var/www/nextcloud/apps/files_fulltextsearch/lib/Service/FilesService.php(896): OCA\Files_FullTextSearch\Service\ExternalFilesService->impersonateOwner(Object(OCA\FullTextSearch\Model\Index))
#2 /var/www/nextcloud/apps/files_fulltextsearch/lib/Service/FilesService.php(491): OCA\Files_FullTextSearch\Service\FilesService->impersonateOwner(Object(OCA\FullTextSearch\Model\Index))
#3 /var/www/nextcloud/apps/files_fulltextsearch/lib/Provider/FilesProvider.php(264): OCA\Files_FullTextSearch\Service\FilesService->updateDocument(Object(OCA\FullTextSearch\Model\Index))
#4 /var/www/nextcloud/apps/fulltextsearch/lib/Service/IndexService.php(401): OCA\Files_FullTextSearch\Provider\FilesProvider->updateDocument(Object(OCA\FullTextSearch\Model\Index))
#5 /var/www/nextcloud/apps/fulltextsearch/lib/Command/Live.php(291): OCA\FullTextSearch\Service\IndexService->updateDocument(Object(OCA\FullTextSearch_ElasticSearch\Platform\ElasticSearchPlatform), Object(OCA\Files_FullTextSearch\Provider\FilesProvider), Object(OCA\FullTextSearch\Model\Index))
#6 /var/www/nextcloud/apps/fulltextsearch/lib/Command/Live.php(258): OCA\FullTextSearch\Command\Live->liveCycle()
#7 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\FullTextSearch\Command\Live->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/nextcloud/core/Command/Base.php(166): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/nextcloud/3rdparty/symfony/console/Application.php(946): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/nextcloud/3rdparty/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OCA\FullTextSearch\Command\Live), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/nextcloud/console.php(96): OC\Console\Application->run()
#14 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')

Please let me know if you need further information

**Comment by theroch** [comment] 2019-01-25 16:40
Same issue on nextcloud 14.0.6., fulltextsearch 1.1.0, fulltextsearch_files 1.1.1, fulltextsearch_ealstic 1.0.2
The external mount is connected to an smb share.

>   ./occ fulltextsearch:index

runs without errors

>   ./occ fulltextsearch:live

crashes with _Call to a member function getStorage() on null_

**Comment by daita** [comment] 2019-01-28 17:33
@theroch this is a known issue that is fixed in NC15

**Comment by p3pp0** [comment] 2019-01-28 17:41
unfortunately it is not @theroch 
https://github.com/nextcloud/fulltextsearch/issues/434#issuecomment-457613318

**Comment by theroch** [comment] 2019-01-29 06:59
I've fixed the null access with a condition by myself.
Now the process does't exit with an exception, but the live index still doesn't work.
I think it has something to do, with the cause of the null exception. Because it only can occur if there is no user.

**Comment by p3pp0** [comment] 2019-01-29 09:46
okay... can you help aus @daita ?

**Comment by daita** [comment] 2019-01-29 09:59
@p3pp0 could it be possible that you used the external storage at one point but disabled the app lately ?

**Comment by p3pp0** [comment] 2019-01-29 10:32
@daita i dont really understand the question. External storage is configured and app is enabled (please see pictures, please ask again if i havent answered your question)

external storage: https://s15.directupload.net/images/190129/9sjxxug5.png
active apps: https://s15.directupload.net/images/190129/ehqlnz37.png

**Comment by daita** [comment] 2019-01-31 17:48
please test last release and let's focus on one bug report

**Closed** 2019-02-12 17:22 UTC
Labels: fixed ?
